targets:
  $default:
    builders:
      json_serializable:
        options:
          create_to_json: false
          explicit_to_json: true
          include_if_null: false
          field_rename: none
