name: tinder_like
description: Test task for Eclipse Digital Studio
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Network
  http: 1.1.0

  # Routing
  go_router: 12.1.1

  # State management
  bloc: 8.1.2
  flutter_bloc: 8.1.3

  # Models
  json_annotation: 4.8.1

  # Localization
  intl: 0.18.1
  flutter_localizations:
    sdk: flutter

  # UI
  cached_network_image: 3.3.0

  # Utils
  meta: 1.9.1
  collection: 1.17.2
  bloc_concurrency: 0.2.2

dev_dependencies:
  # Code generation
  build_runner: 2.4.6
  build_verify: 3.1.0
  json_serializable: 6.7.1
  go_router_builder: 2.3.4

flutter:
  uses-material-design: true
